version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
